# Generated by Django 6.0.1 on 2026-01-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_name', models.CharField(max_length=200, verbose_name='Comic Name')),
                ('issue_num', models.IntegerField(verbose_name='Issue Number')),
                ('pub_date', models.DateField(verbose_name='Date Published')),
                ('era', models.CharField(max_length=200, verbose_name='Era')),
                ('rating', models.IntegerField(verbose_name='Rating')),
            ],
        ),
    ]
