# Generated by Django 6.0.1 on 2026-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='issue_num',
            field=models.IntegerField(null=True, verbose_name='Issue Number'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Rating'),
        ),
    ]
