# Generated by Django 6.0.1 on 2026-01-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_alter_comic_issue_num_alter_comic_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='era',
        ),
        migrations.AddField(
            model_name='comic',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='issue_num',
            field=models.IntegerField(blank=True, default=0, verbose_name='Issue Number'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Loved'), ('4', 'Liked'), ('3', 'Neutral'), ('2', "Didn't Like"), ('1', 'Hated'), ('0', "Don't Know")], default=0, max_length=1, verbose_name='Rating'),
        ),
    ]
