# Generated by Django 6.0.1 on 2026-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_comic_era_comic_read_alter_comic_issue_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='issue_num',
            field=models.IntegerField(blank=True, verbose_name='Issue Number'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='rating',
            field=models.CharField(blank=True, choices=[('5', 'Loved'), ('4', 'Liked'), ('3', 'Neutral'), ('2', "Didn't Like"), ('1', 'Hated')], max_length=1, verbose_name='Rating'),
        ),
    ]
