# Generated by Django 6.0.1 on 2026-01-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_comic_issue_num_alter_comic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='pub_date_exact',
            field=models.BooleanField(default=True, verbose_name='Exact Publication Date Known'),
        ),
    ]
